import 'package:flutter/widgets.dart';

class CustomICons {
  CustomICons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData idCard =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userCheck =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userCircle =
      IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userMinus =
      IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userPin =
      IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userPlus =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userVoice =
      IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userX =
      IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barBottom =
      IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barLeft =
      IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barRight =
      IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barTop =
      IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code =
      IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cylinder =
      IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data =
      IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terminal =
      IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfer =
      IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windowCheck =
      IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windowClose =
      IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windowCodeBlock =
      IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windowSidebar =
      IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windowTerminal =
      IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData window =
      IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData run =
      IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sale =
      IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppingCart =
      IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationActive =
      IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationDeactivated =
      IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationDot =
      IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationMinus =
      IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationOutlineDot =
      IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationOutlineMinus =
      IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationOutlinePlus =
      IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationOutline =
      IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationPlus =
      IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification =
      IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dot01Xs =
      IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dot02S =
      IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dot03M =
      IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dot04L =
      IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dot05Xl =
      IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineL =
      IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineM =
      IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineS =
      IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineSx =
      IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineXl =
      IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closeBig =
      IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closeSmall =
      IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburger =
      IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuAlt01 =
      IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuAlt02 =
      IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuAlt03 =
      IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuAlt04 =
      IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuAlt05 =
      IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuDuo =
      IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moreHorizontal =
      IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moreVertical =
      IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplay =
      IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cast =
      IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fastForward =
      IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fastRewind =
      IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pauseCircleFilled =
      IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pauseCircleOutline =
      IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playArrow =
      IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playCircleFilled =
      IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playCircleOutline =
      IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat =
      IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle =
      IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skipNext =
      IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skipPrevious =
      IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building =
      IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeAltCheck =
      IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeAltFill =
      IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeAltMinus =
      IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeAltOutline =
      IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeAltPlus =
      IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeAltX =
      IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeCheck =
      IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeFill =
      IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeHeart1 =
      IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeHeart =
      IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeMinus =
      IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeOutline =
      IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homePlus =
      IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeX =
      IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard02 =
      IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard =
      IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gridBigRound =
      IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gridBig =
      IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gridHorizontalRound =
      IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gridHorizontal =
      IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gridRound =
      IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gridSmallRound =
      IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gridSmall =
      IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gridVerticalRound =
      IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gridVertical =
      IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid =
      IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffeeCircle =
      IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudCheck =
      IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudClose =
      IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudDown =
      IconData(0xe966, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudOff =
      IconData(0xe967, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudOutline =
      IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudUp =
      IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileArchive =
      IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileBlankFill =
      IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileBlankOutline =
      IconData(0xe96d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileCss =
      IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileDownloadPdf =
      IconData(0xe96f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileFind =
      IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileHtml =
      IconData(0xe971, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileImage =
      IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileJpg =
      IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileJs =
      IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileMinus =
      IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileNew =
      IconData(0xe976, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filePdf =
      IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filePng =
      IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileSvg =
      IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderMinus =
      IconData(0xe97a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderOpen =
      IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderPlus =
      IconData(0xe97c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder =
      IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note =
      IconData(0xe97e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addToQueue =
      IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commentCheck =
      IconData(0xe980, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commentMinus =
      IconData(0xe981, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commentPlus =
      IconData(0xe982, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      IconData(0xe983, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy =
      IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit =
      IconData(0xe985, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide =
      IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listCheck =
      IconData(0xe987, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listMinus =
      IconData(0xe988, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listOl =
      IconData(0xe989, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listPlus =
      IconData(0xe98a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listUl =
      IconData(0xe98b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minusCircleOutline =
      IconData(0xe98c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minusCircle =
      IconData(0xe98d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minusSquare =
      IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus =
      IconData(0xe98f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moveHorizontal =
      IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moveVertical =
      IconData(0xe991, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move =
      IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plusCircleOutline =
      IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plusCircle =
      IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plusSquare =
      IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData searchSmallMinus =
      IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData searchSmallPlus =
      IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData searchSmall =
      IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selectMultiple =
      IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show =
      IconData(0xe99c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textAlignCenter =
      IconData(0xe99d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textAlignJustify =
      IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textAlignLeft =
      IconData(0xe99f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textAlignRight =
      IconData(0xe9a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devices =
      IconData(0xe9a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop =
      IconData(0xe9a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobileAlt =
      IconData(0xe9a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile =
      IconData(0xe9a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor =
      IconData(0xe9a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet =
      IconData(0xe9a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee =
      IconData(0xe9a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barChartAlt =
      IconData(0xe9a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barChartHorizontal =
      IconData(0xe9a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barChartSquare =
      IconData(0xe9aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barChart =
      IconData(0xe9ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doughnutChart =
      IconData(0xe9ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineChartDown =
      IconData(0xe9ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineChartUp =
      IconData(0xe9ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pieChart25 =
      IconData(0xe9af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pieChart50 =
      IconData(0xe9b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pieChart75 =
      IconData(0xe9b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pieChartOutline25 =
      IconData(0xe9b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pieChartOutline =
      IconData(0xe9b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trendingDown =
      IconData(0xe9b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trendingUp =
      IconData(0xe9b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarCalendar =
      IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarCheck =
      IconData(0xe9b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarEdit =
      IconData(0xe9b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarEvent =
      IconData(0xe9b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarMinus =
      IconData(0xe9ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarPlus =
      IconData(0xe9bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarWeek =
      IconData(0xe9bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarX =
      IconData(0xe9bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe9be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adobeXd =
      IconData(0xe9bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appStore =
      IconData(0xe9c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple =
      IconData(0xe9c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance =
      IconData(0xe9c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coolicons =
      IconData(0xe9c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData css3 =
      IconData(0xe9c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discord =
      IconData(0xe9c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble =
      IconData(0xe9c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropbox =
      IconData(0xe9c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      IconData(0xe9c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData figma =
      IconData(0xe9c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github =
      IconData(0xe9ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google =
      IconData(0xe9cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData html5 =
      IconData(0xe9cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram =
      IconData(0xe9cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invision =
      IconData(0xe9ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData javascript =
      IconData(0xe9cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedIn =
      IconData(0xe9d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkpath =
      IconData(0xe9d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messenger =
      IconData(0xe9d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal =
      IconData(0xe9d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playStore =
      IconData(0xe9d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit =
      IconData(0xe9d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sketch =
      IconData(0xe9d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack =
      IconData(0xe9d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat =
      IconData(0xe9d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spectrum =
      IconData(0xe9d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotify =
      IconData(0xe9da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackOverflow =
      IconData(0xe9db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trello =
      IconData(0xe9dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter =
      IconData(0xe9dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unsplash =
      IconData(0xe9de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube =
      IconData(0xe9df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarmAdd =
      IconData(0xe9e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm =
      IconData(0xe9e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bulb =
      IconData(0xe9e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkboxChecked =
      IconData(0xe9e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkboxSquare =
      IconData(0xe9e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox =
      IconData(0xe9e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleCheckOutline =
      IconData(0xe9e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleCheck =
      IconData(0xe9e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleChecked =
      IconData(0xe9e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear =
      IconData(0xe9e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      IconData(0xe9ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cokie =
      IconData(0xe9eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color =
      IconData(0xe9ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData command =
      IconData(0xe9ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData confused =
      IconData(0xe9ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creditCardAlt =
      IconData(0xe9ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creditCard =
      IconData(0xe9f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doneAll =
      IconData(0xe9f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done =
      IconData(0xe9f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downloadDone =
      IconData(0xe9f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      IconData(0xe9f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit =
      IconData(0xe9f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData externalLink =
      IconData(0xe9f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flagFill =
      IconData(0xe9f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flagOutline =
      IconData(0xe9f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy =
      IconData(0xe9f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartFill =
      IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartOutline =
      IconData(0xe9fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helpCircleOutline =
      IconData(0xe9fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helpCircle =
      IconData(0xe9fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helpQuestionmark =
      IconData(0xe9fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imageAlt =
      IconData(0xe9ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData label =
      IconData(0xea00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layersAlt =
      IconData(0xea01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers =
      IconData(0xea02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link02 =
      IconData(0xea03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      IconData(0xea04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loading =
      IconData(0xea05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationOutline =
      IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logOut =
      IconData(0xea08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mailOpen =
      IconData(0xea09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail =
      IconData(0xea0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map =
      IconData(0xea0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon =
      IconData(0xea0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offClose =
      IconData(0xea0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offOutlineClose =
      IconData(0xea0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path =
      IconData(0xea0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone =
      IconData(0xea10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radioFilled =
      IconData(0xea11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio =
      IconData(0xea12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh02 =
      IconData(0xea13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh =
      IconData(0xea14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData run1 =
      IconData(0xea15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad =
      IconData(0xea16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingsFilled =
      IconData(0xea17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingsFuture =
      IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings =
      IconData(0xea19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shareOutline =
      IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share =
      IconData(0xea1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData choppingCart1 =
  //     IconData(0xea1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slider01 =
      IconData(0xea1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slider02 =
      IconData(0xea1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slider03 =
      IconData(0xea1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stopwatch =
      IconData(0xea20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun =
      IconData(0xea21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tagOutline =
      IconData(0xea22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      IconData(0xea23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trashEmpty =
      IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trashFull =
      IconData(0xea25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlink =
      IconData(0xea26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData errorOutline =
      IconData(0xea27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error =
      IconData(0xea28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infoCircleOutline =
      IconData(0xea29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infoCircle =
      IconData(0xea2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infoSquareOutline =
      IconData(0xea2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infoSquare =
      IconData(0xea2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warningOutline =
      IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning =
      IconData(0xea2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shortRight =
      IconData(0xea2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caretDown =
      IconData(0xea30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caretLeft =
      IconData(0xea31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caretRight =
      IconData(0xea32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caretUp =
      IconData(0xea33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronBigDown =
      IconData(0xea34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronBigLeft =
      IconData(0xea35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronBigRight =
      IconData(0xea36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronBigUp =
      IconData(0xea37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronDown =
      IconData(0xea38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronDuoDown =
      IconData(0xea39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronDuoLeft =
      IconData(0xea3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronDuoRight =
      IconData(0xea3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronDuoUp =
      IconData(0xea3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronLeft =
      IconData(0xea3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronRightForCells =
      IconData(0xea3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronRight =
      IconData(0xea3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronUp =
      IconData(0xea40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleChevronDown =
      IconData(0xea41, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleChevronLeft =
      IconData(0xea42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleChevronRight =
      IconData(0xea43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleChevronUp =
      IconData(0xea44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleDown =
      IconData(0xea45, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleLeft =
      IconData(0xea46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleRight =
      IconData(0xea47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleUp =
      IconData(0xea48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand =
      IconData(0xea49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firstPage =
      IconData(0xea4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lastPage =
      IconData(0xea4b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData longBottomDown =
      IconData(0xea4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData longBottomUp =
      IconData(0xea4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData longDown =
      IconData(0xea4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData longLeft =
      IconData(0xea4f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData longRight =
      IconData(0xea50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData longUpLeft =
      IconData(0xea51, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData longUpRight =
      IconData(0xea52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData longUp =
      IconData(0xea53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shortDown =
      IconData(0xea54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shortLeft =
      IconData(0xea55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shortRight1 =
      IconData(0xea56, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shortUp =
      IconData(0xea57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shrink =
      IconData(0xea58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smallLongDown =
      IconData(0xea59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smallLongLeft =
      IconData(0xea5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smallLongRight =
      IconData(0xea5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smallLongUp =
      IconData(0xea5c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subLeft =
      IconData(0xea5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subRight =
      IconData(0xea5e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinBigDown =
      IconData(0xea5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinBigLeft =
      IconData(0xea60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinBigRight =
      IconData(0xea61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinBigUp =
      IconData(0xea62, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinLong02Down =
      IconData(0xea63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinLong02Left =
      IconData(0xea64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinLong02Right =
      IconData(0xea65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinLong02Up =
      IconData(0xea66, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinLongDown =
      IconData(0xea67, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinLongLeft =
      IconData(0xea68, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinLongRight =
      IconData(0xea69, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinLongUp =
      IconData(0xea6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unfoldLess =
      IconData(0xea6b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unfoldMore =
      IconData(0xea6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bonus =
      IconData(0xea6d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffeeBig =
      IconData(0xea6e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppingCart2 =
      IconData(0xea6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData communications =
      IconData(0xea70, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mailOpen1 =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
