name: Flutter iOS Build for AltStore

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Install CocoaPods Dependencies
      run: |
        cd ios
        pod install --repo-update
        cd ..

    - name: Build Flutter iOS (No Sign)
      run: |
        # Флаг --output принудительно сохранит билд в созданную нами папку
        flutter build ios --no-codesign --release --output=$PWD/build_output

    - name: Prepare APP folder for AltStore
      run: |
        mkdir -p Payload
        # Копируем приложение напрямую из папки вывода
        cp -r build_output/Runner.app Payload/
        zip -r Partner.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: partner-ios-app
        path: Partner.ipa
