name: Flutter iOS Build for AltStore

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Install CocoaPods Dependencies
      run: |
        cd ios
        pod install --repo-update
        cd ..

    - name: Build Flutter iOS (No Sign)
      run: |
        flutter build ios --no-codesign --release

    - name: Prepare APP folder for AltStore
      run: |
        mkdir -p Payload
        # Ищем Runner.app по всей рабочей директории GitHub Actions
        APP_PATH=$(find /Users/runner/Library/Developer/Xcode/DerivedData -name "Runner.app" -type d | head -n 1)
        
        # Если в DerivedData не нашли, ищем в локальной папке проекта
        if [ -z "$APP_PATH" ]; then
          APP_PATH=$(find . -name "Runner.app" -type d | head -n 1)
        fi
        
        if [ -z "$APP_PATH" ]; then
          echo "Ошибка: Файл Runner.app не найден ни в одной папке!"
          exit 1
        fi
        
        echo "Успешно найден Runner.app по пути: $APP_PATH"
        cp -r "$APP_PATH" Payload/
        zip -r Partner.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: partner-ios-app
        path: Partner.ipa
